- hosts: localhost
  become: yes
  tasks:
    - name: Add repository for Debian OS family
      block:
      - name: Ensure keyring directory exists
        ansible.builtin.file:
          path: /etc/apt/keyrings
          state: directory
          mode: '0755'

      - name: Add HashiCorp GPG key to keyring
        ansible.builtin.command: gpg --dearmor -o /etc/apt/keyrings/hashicorp-archive-keyring.gpg /tmp/hashicorp.gpg
        args:
          creates: /etc/apt/keyrings/hashicorp-archive-keyring.gpg

      - name: Add HashiCorp repository
        ansible.builtin.apt_repository:
          repo: "deb [signed-by=/etc/apt/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
          filename: hashicorp
          update_cache: no  # We'll update manually after

      - name: Update package cache
        apt:
          update_cache : true
      when: ansible_facts['os_family'] == "Debian"


    - name: Add repository for RedHat OS family
      block:
        - name: Add HashiCorp repository for Fedora
          ansible.builtin.get_url:
            url: "https://rpm.releases.hashicorp.com/fedora/hashicorp.repo"
            dest: /etc/yum.repos.d/hashicorp.repo
            mode: '0644'

        - name: Refresh package cache
          ansible.builtin.dnf:
            update_cache: yes
      when: ansible_facts['os_family'] == "RedHat"

    - name: Install terraform 
      ansible.builtin.package:
        name: terraform
        state: latest

